# Site settings
title: With everyone ALL IN- It's Easy
#header-img: img/home-bg.jpg
header-img: img/hm.jpg
email: dennisfisher168@gmail.com
copyright_name: ALL IN
description: "Write your site description here. It will be used as your sites meta description as well!"
#baseurl: "/startbootstrap-clean-blog-jekyll"
baseurl: "/charity"
url: "http://yourdomain.com"
twitter_username: SBootstrap
github_username:  davidtmiller
facebook_username:  StartBootstrap
email_username:  dennisfisher168@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 2
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
